version: "3"

services:
  # This container contains both a beam proxy (proxy1.broker) and the secret sync local component (secret-sync.proxy1.broker)
  local:
    build:
      context: ../
      dockerfile: Dockerfile.local
    environment:
      - PROXY_ID=proxy1.broker
      - GITLAB_PROJECT_ACCESS_TOKEN_PROVIDER=app2.proxy2.broker
      - BROKER_URL=http://broker:8080
      - SECRET_DEFINITIONS=${ARGS}
    volumes:
      # By default the secret sync local component writes to /usr/local/cache inside the container
      - ${CACHE_PATH}:/usr/local/cache
    extra_hosts:
      # Containers can access the host at 172.17.0.1
      - "broker:172.17.0.1"
    secrets:
      - privkey.pem
      - root.crt.pem

  # This container contains the secret sync central component (app2.proxy2.broker)
  central:
    build:
      context: ../
      dockerfile: Dockerfile.central
    environment:
      - BEAM_URL=http://proxy:8082
      - BEAM_ID=app2.proxy2.broker
      - BEAM_SECRET=App1Secret
      - GITLAB_URL=https://git.verbis.dkfz.de/
      - GITLAB_API_ACCESS_TOKEN=YjTXxdzLMak-XXscyxy4
    extra_hosts:
      # Containers can access the host at 172.17.0.1
      - "proxy:172.17.0.1"

secrets:
  privkey.pem:
    file: ${BEAM_DIR}/dev/pki/proxy1.priv.pem
  root.crt.pem:
    file: ${BEAM_DIR}/dev/pki/root.crt.pem
