version: "3"

# Use the run.sh script when running this docker-compose.yaml. This docker-compose.yaml only works in conjunction with the dev/beamdev
# script and corresponding docker-compose.yaml in the beam repository. That scripts sets up a beam network with one broker and two
# proxies. Only the broker (broker) and the second proxy (proxy2.broker) are used here.

services:
  # This container contains both a beam proxy (proxy1.broker) and the secret sync local component (secret-sync.proxy1.broker)
  local:
    build:
      context: ../
      dockerfile: Dockerfile.local
    environment:
      - PROXY_ID=proxy1.broker
      - OIDC_PROVIDER=app2.proxy2.broker
      - BROKER_URL=http://broker:8080
      - SECRET_DEFINITIONS=${ARGS}
    volumes:
      # By default the secret sync local component writes to /usr/local/cache inside the container
      - ${CACHE_PATH}:/usr/local/cache
    extra_hosts:
      # Containers can access the host at 172.17.0.1
      - "broker:172.17.0.1"
    secrets:
      - privkey.pem
      - root.crt.pem

  # This container contains the secret sync central component (app2.proxy2.broker)
  central:
    build:
      context: ../
      dockerfile: Dockerfile.central
    environment:
      - BEAM_URL=http://proxy:8082
      - BEAM_ID=app2.proxy2.broker
      - BEAM_SECRET=App1Secret
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ID=admin
      - KEYCLOAK_SECRET=admin
      - KEYCLOAK_SERVICE_ACCOUNT_ROLES=query-users
    extra_hosts:
      # Containers can access the host at 172.17.0.1
      - "proxy:172.17.0.1"

secrets:
  privkey.pem:
    file: ${BEAM_DIR}/dev/pki/proxy1.priv.pem
  root.crt.pem:
    file: ${BEAM_DIR}/dev/pki/root.crt.pem
